spring.application.name=heartwave-backend

spring.datasource.url=${HEARTWAVE_DATABASE_URL:jdbc:postgresql://localhost:5433/musicbrainz_db}
spring.datasource.username=${HEARTWAVE_DATABASE_USERNAME:musicbrainz}
spring.datasource.password=${HEARTWAVE_DATABASE_PASSWORD:musicbrainz}

spring.flyway.enabled=true
spring.flyway.default-schema=heartwave
spring.flyway.schemas=heartwave
spring.flyway.create-schemas=true

management.endpoints.web.exposure.include=health,info
